### ISSUE TITLE
浏览器输入127.0.0.1:7079/ui/，没界面展示

### ISSUE THREAD

**Issue by vboy1010** [shunfei/cronsun#10]
Please answer these questions before submitting your issue. Thanks!
在你提交 issue 前，请先回答以下问题，谢谢！

1. What version of Go and cronsun version are you using?
你用的是哪个版本的 Go 和 哪个版本的 cronsun？
go version go1.8.1 linux/amd64
2. What operating system and processor architecture are you using (`go env`)?
你用的是哪个操作系统，什么架构的？
centos6， x86 64

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
你做了什么，遇到了什么问题？尽可能描述清楚问题，最好把操作步骤写下来，按这些步骤操作后能重现你的问题。
在浏览器输入：http://127.0.0.1:7079/ui/
界面显示一个图片，什么都没有加载

![image](https://cloud.githubusercontent.com/assets/2010071/26399925/58472d44-40b1-11e7-9145-db2293416bc3.png)

4. What did you expect to see?
你期望得到什么样的结果？
可以展示出和您的文档中的正常界面即可

5. What did you see instead?
现在你得到的结果是什么样的？
如上图所示

**Comment by miraclesu** [comment]
1. 按你的描述无法重现你的问题，不知道你的执行文件从哪里来，配置是什么，如何启动。
2. 你可以尝试检查一下 `web.json` 里的 `UIDir` 这项配置，这个路径下应该有 `build.js` 这个文件。
3. 你可以下载一个 https://github.com/shunfei/cronsun/releases 发布版解压对比看看是不是 `ui` 这个文件夹里少了什么文件。

**Comment by QLeelulu** [comment]
换chrome浏览器试一下

**Comment by vboy1010** [comment]
的确是浏览器问题，低版本的firefox不支持，我升级到最新版本，就正常了，多谢两位

**Comment by vboy1010** [comment]
碰到新的问题了，执行脚本时，一直失败，错误信息如下：

![image](https://cloud.githubusercontent.com/assets/2010071/26435180/f67046de-413f-11e7-902e-85e813fd853f.png)

任务配置如下图所示：
![image](https://cloud.githubusercontent.com/assets/2010071/26435159/c5952886-413f-11e7-996f-98cda65b56ce.png)

**Comment by vboy1010** [comment]
【问题已经找到解决方法】
[root@xxx dist]  ./cronnode -conf conf/base.json
这里换成root用户执行，配置的任务才能执行成功。那么其他用户为什么不行呢？

另外，任务脚本，.php后缀，
需要在php脚本的开头加上#! /bin/env php，这样PHP脚本才能执行，个人认为系统应该自动判断处理，而不是脚本去加这么一行代码。

**Comment by miraclesu** [comment]
1. 关于 `root` 用户执行，新版本处理了一下这个问题，如果 `cronnode` 以 `vboy` 用户启动，任务指定这个用户执行，新版本可以执行成功了
2. `cronsun` 只负责执行脚本，和 `crontab` 一样，不会对脚本进行额外的处理，理论上命令行里能执行成功的脚本在 `cronsun` 里也能执行成功，反之亦然
