### ISSUE TITLE
搭建起来，在web界面没有看见相关节点信息？

### ISSUE THREAD

**Issue by shineforever** [shunfei/cronsun#11]
Please answer these questions before submitting your issue. Thanks!
在你提交 issue 前，请先回答以下问题，谢谢！

1. What version of Go and cronsun version are you using?
你用的是哪个版本的 Go 和 哪个版本的 cronsun？

2. What operating system and processor architecture are you using (`go env`)?
你用的是哪个操作系统，什么架构的？

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
你做了什么，遇到了什么问题？尽可能描述清楚问题，最好把操作步骤写下来，按这些步骤操作后能重现你的问题。

4. What did you expect to see?
你期望得到什么样的结果？ubuntucronsun-v0.1-linux-amd64

5. What did you see instead?
现在你得到的结果是什么样的？

操作系统：ubuntu 
安装cronsun版本：cronsun-v0.1-linux-amd64(直接运行，node节点没有安装go)
etcd安装情况：
![image](https://cloud.githubusercontent.com/assets/1472799/26442247/4453a636-4166-11e7-8b12-3cec6d8b1c57.png)

web端启动报错：
![image](https://cloud.githubusercontent.com/assets/1472799/26442283/690ad7ce-4166-11e7-82bc-8253d9431825.png)

node端启动报错：
![image](https://cloud.githubusercontent.com/assets/1472799/26442317/940960ee-4166-11e7-8b34-690071244c8d.png)

安装文档好简单，有些地方理解不完全，麻烦作者看看，非常感谢

**Comment by QLeelulu** [comment]
确认下配置中的etcd配置IP和端口是否正确。

@miraclesu 出错的时候日志打印下IP和端口？

**Comment by shineforever** [comment]
etcd启动脚本：
![image](https://cloud.githubusercontent.com/assets/1472799/26443516/516046cc-416b-11e7-864f-d0a6350fcf0f.png)

**Comment by shineforever** [comment]
![image](https://cloud.githubusercontent.com/assets/1472799/26444505/474793ee-416f-11e7-972d-52df7c263d7d.png)

**Comment by miraclesu** [comment]
@shineforever 
1.  `etcd` 的配置指的是 `conf/etcd.json` 里的 `Endpoints` 项，不是指你启动 `etcd` 时的配置
2.  再检查一下 `conf/db.json` 里的配置，看看 MongoDB 的 IP 和端口是否对得上

**Comment by shineforever** [comment]
以上问题解决了，但是启动的时候是正常的，有时候确实404？
![image](https://cloud.githubusercontent.com/assets/1472799/26486299/10b5caf8-422d-11e7-8560-6081e0211cbd.png)

**Comment by shineforever** [comment]
以上问题解决了，但是启动感觉不稳定啊，有时候可以web访问，但是有时候启动，又是404？
![image](https://cloud.githubusercontent.com/assets/1472799/26486335/3e8dd42a-422d-11e7-8e88-4dcfca87aa75.png)

**Comment by shineforever** [comment]
启动命令要不就是前台启动，要不就是通过screen启动？后台运行，后面加&，都运行不成功！！！

**Comment by QLeelulu** [comment]
修改下 conf/files/web.json 配置里面的，`"UIDir": "ui"` 为完整的路径试试看，
例如：

```
"UIDir": "/path/to/your/cronsun/web/ui"
```
