### ISSUE TITLE
sh build.sh 报错了

### ISSUE THREAD

**Issue by kouga-huang** [shunfei/cronsun#12]
Please answer these questions before submitting your issue. Thanks!
在你提交 issue 前，请先回答以下问题，谢谢！

1. What version of Go and cronsun version are you using?
你用的是哪个版本的 Go 和 哪个版本的 cronsun？
go:1.8.1 cronsun:master
2. What operating system and processor architecture are you using (`go env`)?
你用的是哪个操作系统，什么架构的？
osx

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
你做了什么，遇到了什么问题？尽可能描述清楚问题，最好把操作步骤写下来，按这些步骤操作后能重现你的问题。
执行：sh build.sh 
报错：./conf/files/base.json.sample: Permission denied  
你好，我看了build.sh文件，为什么会使用bash执行json文件

4. What did you expect to see?
你期望得到什么样的结果？
我期望能够支持我进行源码安装

5. What did you see instead?
现在你得到的结果是什么样的？

**Comment by miraclesu** [comment]
已经修复了，用最新的代码就可以了

**Comment by kouga-huang** [comment]
有没有考虑实现任务队列

**Comment by miraclesu** [comment]
你可以先详细描述一下任务队列，然后我们再评估看看

**Comment by kouga-huang** [comment]
你好，
现在执行任务的方式是在node本节点下上传对应的任务执行脚本，然后由node调度执行。

我的想法是：是由各个业务系统生产任务包，然后进入到任务队列，任务包需指明如何去执行该任务，如通过http等方式
然后由node去消费任务队列，消费每个任务包。并记录每个任务包的执行结果

不知道我的描述，你能否明白？

**Comment by kouga-huang** [comment]
因为我刚好有项目有这个需要。然后你这个开源项目挺好的，支持分布式，支持crontab 。

**Comment by miraclesu** [comment]
这个系统的 `web` 是调用 API 把任务存到 `etcd` 的，你在业务系统里把 job 组织好，通过 `PUT /job` 创建 job 即可满足你的需求。API 现在没有文档，你可以在 web 下通过新建一个 job 看一下具体参数。

**Comment by kouga-huang** [comment]
好的 多谢
