### ISSUE TITLE
node节点watch机制失效，任务暂停依然执行

### ISSUE THREAD

**Issue by GodTou** [shunfei/cronsun#121]
Please answer these questions before submitting your issue. Thanks!
在你提交 issue 前，请先回答以下问题，谢谢！

1. What version of Go and cronsun version are you using?
你用的是哪个版本的 Go 和 哪个版本的 cronsun？
go 1.11
cronsun v0.3.4

2. What operating system and processor architecture are you using (`go env`)?
你用的是哪个操作系统，什么架构的？
Centos 6.5 amd64

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
你做了什么，遇到了什么问题？尽可能描述清楚问题，最好把操作步骤写下来，按这些步骤操作后能重现你的问题。

某些node节点watch机制失效，无法同步任务修改事件

4. What did you expect to see?
你期望得到什么样的结果？

任务暂停，修改，删除，节点能正常同步任务状态

5. What did you see instead?
现在你得到的结果是什么样的？

目前出现两次 node watch中断的问题，导致暂停和删除的任务正常在该节点调度

**Comment by QLeelulu** [comment]
用的etcd是哪个版本呢？

**Comment by GodTou** [comment]
> 用的etcd是哪个版本呢？

etcdctl version: 3.3.10
API version: 3.3

**Comment by GodTou** [comment]
@QLeelulu 

> Progress_Notify - When set, the watch will periodically receive a WatchResponse with no events, if there are no recent events. It is useful when clients wish to recover a disconnected watcher starting from a recent known revision. The etcd server decides how often to send notifications based on current server load.

不知道watchRequest中的这个字段是否有帮助，etcd我这边刚开始玩耍，还不熟，我看cronsun的watch Request 的opts里没有设置这个。

**Comment by QLeelulu** [comment]
谢谢。
可以发一下没生效的任务ID，和对应的cronnode节点日志看一下？

**Comment by QLeelulu** [comment]
```
etcdctl cluster-health
```

用这个命令看看etcd集群是否正常？
怎么看到两个cronnode节点更新的内容都有差异。
例如
```
2018-11-26T15:27:56.217+0800 INFO node/node.go:270 job[f9acc018] group[Finance] rule[f8acc018] timer[0 1 0 * * *] has added
```
这个在正常节点相同时间点并没有看到对应的日志

**Comment by GodTou** [comment]
> ```
> etcdctl cluster-health
> ```
> 用这个命令看看etcd集群是否正常？
> 怎么看到两个cronnode节点更新的内容都有差异。
> 例如
> 
> ```
> 2018-11-26T15:27:56.217+0800 INFO node/node.go:270 job[f9acc018] group[Finance] rule[f8acc018] timer[0 1 0 * * *] has added
> ```
> 这个在正常节点相同时间点并没有看到对应的日志
```
etcdctl endpoint health

172.21.12.186:2379 is healthy: successfully committed proposal: took = 570.227µs
172.21.12.184:2379 is healthy: successfully committed proposal: took = 909.463µs
172.21.12.185:2379 is healthy: successfully committed proposal: took = 759.799µs
```
两个节点的日志差异是这两个节点启动有先后顺序，正常节点14:25就启动，然后进行了任务创建修改，异常节点 15:27才启动，这时候只是进行了任务同步，任务是选了这两个节点组成的一个group进行执行的，设置的是单机单进程

**Comment by QLeelulu** [comment]
`etcdctl endpoint status -w table` 这个命令再看下 ？

**Comment by GodTou** [comment]
> `etcdctl endpoint --cluster status -w table` 这个命令再看下 ？

+--------------------+------------------+---------+---------+-----------+-----------+------------+
|      ENDPOINT      |        ID        | VERSION | DB SIZE | IS LEADER | RAFT TERM | RAFT INDEX |
+--------------------+------------------+---------+---------+-----------+-----------+------------+
| :2379 | e20b8da8ecbc3363 |  3.3.10 |  242 MB |     false |       107 |    5556450 |
| :2379 |  ca3c4cdc869af0f |  3.3.10 |  242 MB |     false |       107 |    5556451 |
| :2379 |  685b0ebcb18cd06 |  3.3.10 |  242 MB |      true |       107 |    5556452 |
+--------------------+------------------+---------+---------+-----------+-----------+------------+

**Comment by QLeelulu** [comment]
QQ交流群： 123731057

你加下Q群？
