### ISSUE TITLE
能否完善wiki，把系统架构和交互细节在说详细点

### ISSUE THREAD

**Issue by shineforever** [shunfei/cronsun#13]
Please answer these questions before submitting your issue. Thanks!
在你提交 issue 前，请先回答以下问题，谢谢！

1. What version of Go and cronsun version are you using?
你用的是哪个版本的 Go 和 哪个版本的 cronsun？

2. What operating system and processor architecture are you using (`go env`)?
你用的是哪个操作系统，什么架构的？

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
你做了什么，遇到了什么问题？尽可能描述清楚问题，最好把操作步骤写下来，按这些步骤操作后能重现你的问题。

4. What did you expect to see?
你期望得到什么样的结果？

5. What did you see instead?
现在你得到的结果是什么样的？

作者你好，能否完善wiki，把系统架构和交互细节在说详细点；目前使用了段时间，暂时发现以下几个问题：
1）程序启动经常404？
2）cronnode没启动，cronweb启动后正常，过段时间再访问，会出现404？
3）cronweb需要连接mongodb？这主要是获取什么信息，我理解计划任务的推送是通过cronweb推送的啊？

**Comment by miraclesu** [comment]
1. 根据描述无法定位问题
2. 同 1
3. 架构图里已经有整个流程了，`cronweb` 里的任务通过 `etcd` 分发到各个 `cronnode`，`cronnode` 执行完任务后，把任务输出写到 `mongo`，`cronweb` 连接 `mongo` 查询执行结果。

**Comment by shineforever** [comment]
那cronweb端go主要作用就是web是吧？cronnode从etcd获取计划任务这个是轮询方式获取还是什么方式触发啊？

**Comment by miraclesu** [comment]
1. 对，`cronweb` 的主要作用是提供管理后台，go 的作用是提供 API 服务
2. `cronnode` 取任务是直接加载 `etcd` 里面的所有任务，然后过滤出所需的任务，至于任务的更新，用的是 `etcd` 的监听机制，具体你可以去研究一下。
