### ISSUE TITLE
暂停的任务，一个月后重新被打开并执行（无人工干预）

### ISSUE THREAD

**Issue by icarus910** [shunfei/cronsun#133]
Please answer these questions before submitting your issue. Thanks!
在你提交 issue 前，请先回答以下问题，谢谢！

1. What version of Go and cronsun version are you using?
你用的是哪个版本的 Go 和 哪个版本的 cronsun？
v0.3.2 (build go1.10.2)

2. What operating system and processor architecture are you using (`go env`)?
你用的是哪个操作系统，什么架构的？
centos7

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
你做了什么，遇到了什么问题？尽可能描述清楚问题，最好把操作步骤写下来，按这些步骤操作后能重现你的问题。
1月14号关闭的脚本，在一个月后（2月14号）重新被打开了（无人工干预）。

4. What did you expect to see?
你期望得到什么样的结果？
解决这个问题。

5. What did you see instead?
现在你得到的结果是什么样的？
没有解决这个问题。

**Comment by QLeelulu** [comment]
重新打开是什么意思 ？

**Comment by icarus910** [comment]
> 重新打开是什么意思 ？

本来是暂停的状态，自动转为开启的状态了

**Comment by QLeelulu** [comment]
> > 重新打开是什么意思 ？
> 
> 本来是暂停的状态，自动转为开启的状态了

是否误操作了你不知道？或者是其他人操作了？
不可能会自动开启的。
