### ISSUE TITLE
部分任务不运行了

### ISSUE THREAD

**Issue by topicgit** [shunfei/cronsun#134]
Please answer these questions before submitting your issue. Thanks!
在你提交 issue 前，请先回答以下问题，谢谢！

1. What version of Go and cronsun version are you using?
你用的是哪个版本的 Go 和 哪个版本的 cronsun？
cronsun-v0.3.5 直接下载的release包
2. What operating system and processor architecture are you using (`go env`)?
你用的是哪个操作系统，什么架构的？
centos 7 3.10.0-327.22.2.el7.x86_64
node01: etcd mongodb  cronsun-web
node02: etcd mongodb
node03: etcd mongodb
agent01: cronsun-node
agent02: cronsun-node

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
你做了什么，遇到了什么问题？尽可能描述清楚问题，最好把操作步骤写下来，按这些步骤操作后能重现你的问题。
1. mongodb节点出现问题，主节点变成从，之后我恢复了回来
2.目前有一些任务无缘无故的就不执行了，日志中也没有内容；重新创建的job就可以执行，在日志中也可以查看到，请问应当如何进行排查，目前etcd和mongodb的状态正常，任务系统有很多任务不执行了，目前修复方法只能是创建新的job暂停原来的
![image](https://user-images.githubusercontent.com/11975460/53849844-4b55e000-3ff4-11e9-8b66-4c189f7638ac.png)

4. What did you expect to see?
你期望得到什么样的结果？
处于运行状态的任务正常运行

5. What did you see instead?
现在你得到的结果是什么样的？
处于运行状态的任务正常运行

**Comment by QLeelulu** [comment]
不执行是指贴图上显示的执行失败了，还是完全没有调度呢 ？

**Comment by topicgit** [comment]
@QLeelulu 是完全没有调度

**Comment by topicgit** [comment]
某些任务不调度了，这如何查？

**Comment by QLeelulu** [comment]
@topicgit 不调度的任务，在cronnode节点上执行的时候，会在本机输出日志吗？
我怀疑是不是任务是正常调度的，只是任务日志没有写入到mongodb而已，你有办法确认下这个吗？

**Comment by topicgit** [comment]
![image](https://user-images.githubusercontent.com/11975460/53948267-67e03e00-4102-11e9-97a0-fd862d3a39d1.png)

node的日志里面没有任务的信息，任务面板上这个任务上次执行时间是03-05 14:22 下次是03:07 ，03 05的时候mongo状态出现过问题，但是已经修复。 
目前新增的任务没有问题，有部分任务是有问题，很诡异.
node上只有下面这些日志，请问这个会有什么影响？
![image](https://user-images.githubusercontent.com/11975460/53948590-21d7aa00-4103-11e9-8bf6-e901fa119889.png)

**Comment by QLeelulu** [comment]
任务日志如果比较大、秒级任务又比较多的话，需要注意下，会导致日志量太多可能会把mongodb跑挂了。

**Comment by topicgit** [comment]
![image](https://user-images.githubusercontent.com/11975460/56010043-97432580-5d14-11e9-80ed-a79b5c5f2172.png)
请问这是什么原因
