### ISSUE TITLE
Failed to store session

### ISSUE THREAD

**Issue by billhezhiwen** [shunfei/cronsun#135]
Please answer these questions before submitting your issue. Thanks!
在你提交 issue 前，请先回答以下问题，谢谢！

1. What version of Go and cronsun version are you using?
你用的是哪个版本的 Go 和 哪个版本的 cronsun？

2. What operating system and processor architecture are you using (`go env`)?
你用的是哪个操作系统，什么架构的？

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
你做了什么，遇到了什么问题？尽可能描述清楚问题，最好把操作步骤写下来，按这些步骤操作后能重现你的问题。

4. What did you expect to see?
你期望得到什么样的结果？

5. What did you see instead?
现在你得到的结果是什么样的？

**Comment by billhezhiwen** [comment]
2019-03-06T09:52:48.042+0800    ERROR   session/session.go:50   Failed to store session[nDR6DvUScML5tzRPB9A4gsCyaR6nLYPd]: rpc error: code = Internal desc = Unexpected error from context packet: context deadline exceeded: etcd([http://127.0.0.1:2379]) maybe lost

登陆进去后操作就会被登出，检查了etcd的配置也没什么问题

**Comment by Doflatango** [comment]
错误原因是连不上 etcd。

另外：你用的应该是比较久的版本了？或者自己编译的话并且没有使用 go mod 的话，grpc 包可能比较旧了；
