### ISSUE TITLE
因为触发任务并行数上限而产生的失败日志感觉没必要展示吧？会让重要的日志得不到显示

### ISSUE THREAD

**Issue by billhezhiwen** [shunfei/cronsun#137]
![image](https://user-images.githubusercontent.com/16872492/54413502-e0fa1980-4730-11e9-8ac5-fec54c4493cc.png)
job[/cronsun/cmd/asd/bdfb5155] running on[53fce008-471a-4031-9561-80e1d37ec63b] running:[6]

**Comment by QLeelulu** [comment]
#105

**Comment by billhezhiwen** [comment]
1
