### ISSUE TITLE
请问 jodId 生成规则是否会出现重复

### ISSUE THREAD

**Issue by happyzhouhuan** [shunfei/cronsun#138]
作者你好，本人使用java语言开发，对go不是很了解。
看了 id.go 文件中 jobId生成是通过方法 
func NextID() string {
	id := generator.Next()
	return hex.EncodeToString(id[:4])
}
请问一下，该随机的id生成是否会出现重复，确实本人在项目开发测试过程中，出现了id重复情况（通过查看mango库），然后是否会对系统造成影响呢？

**Comment by QLeelulu** [comment]
https://github.com/rogpeppe/fastuuid
不确定你是怎么测试的，用的这个库，应该是不会重复的

**Comment by Doflatango** [comment]
生成 UUID 本有 24 个字节，只截取前 4 个字节在 web 进程多次重启之后是有生成重复 ID  的可能。重启多少次会出现重复不能确定。重复的 ID 等于覆盖更新了原先存在的任务。

**Comment by hellojujian** [comment]
@QLeelulu 请问该bug的PR何时能merge？我们打算尝试使用，有点不放心
另外项目还打算继续维护吗？已经有好几个月未有commit了；

**Comment by QLeelulu** [comment]
@hellojujian 项目是会继续维护的，我们公司内部也在用
