### ISSUE TITLE
cronsun执行脚本和crontab中命令有什么区别

### ISSUE THREAD

**Issue by melpozhang** [shunfei/cronsun#14]
我测试了下cronsun添加任务使用 >> 重定向输出会报错,不是很清楚其中实现原理,请教一下

**Comment by miraclesu** [comment]
目前只支持 `命令` + `参数...` 这种形式，如果需要重定向，可以写一个脚本，在脚本里重定向，把这个脚本(加上执行权限)做为一个任务即可。

**Comment by melpozhang** [comment]
后期考虑支持么, 因为像重定向以及管道之类的用的还是蛮多的,有些简单的任务写个脚本再添加任务还是有些许麻烦

**Comment by miraclesu** [comment]
1. 暂时没有计划，这样做可操作太多，不是很安全
2. 可以增加一个同步脚本任务，这样可以在源机器上写好脚本，然后执行一次这个同步任务，即可把新的脚本同步到目标结点，再增加新脚本做为任务即可
