### ISSUE TITLE
任务失败邮件通知功能该如何配置

### ISSUE THREAD

**Issue by melpozhang** [shunfei/cronsun#15]
conf中的mail配置修改之后,enable改成true,web就起不来了,应该怎么配置呢

**Comment by miraclesu** [comment]
你提供的信息太少，无法定位问题。

你可以尝试检查一下 `mail.json` 里 `smtp` 相关的配置，如果配置有问题，`web` 服务无法连接 `smtp` 服务器，会无法启动。

**Comment by melpozhang** [comment]
thanks 似乎是我们公司邮箱服务器的问题,我后来改用163的smtp服务器就ok了,但是用公司邮箱就会起不来...同样配置信息python客户端可以发邮件...

**Comment by melpozhang** [comment]
解决了...看了下源码,golang标准包smtp只支持CRAMMD5和PLAIN两种认证,而公司服务器只支持GSSAPI NTLM LOGIN,自己实现个认证就解决了
