### ISSUE TITLE
定时任务只支持脚本，如何实现复杂的调用逻辑？

### ISSUE THREAD

**Issue by Mrdshu** [shunfei/cronsun#152]
遇到的问题：
目前看到的定时任务都是脚本方法执行的。
如果定时任务业务逻辑比较复杂，譬如需要查数据库，rpc调多个service的接口。每个定时任务都写成脚本，不是会很麻烦？

4. 期望的结果
想知道目前只支持shell脚本运行的话，是如何支持线上代码中定时任务的执行的。还是说要二次开发才能支持

**Comment by Mrdshu** [comment]
目前看，不支持非shell脚本执行。只能二次开发

**Comment by mofadeyunduo** [comment]
请问最近有没有关于这一方面的计划？
