### ISSUE TITLE
修改任务所属分组会导致删除任务

### ISSUE THREAD

**Issue by melpozhang** [shunfei/cronsun#16]
比如一个已经存在的任务,修改任务组,从cronnode的控制台打印信息来看会删除这个job,在web上还是可以找到,然后点开重新点一下保存,控制台就打印added.
2017-06-12T17:51:56.281+0800	INFO	log/log.go:26	job[1aacb776] rule[19acb776] timer[*/15 * * * * *] has deleted
2017-06-12T17:56:28.784+0800	INFO	log/log.go:26	job[1aacb776] rule[19acb776] timer[*/15 * * * * *] has added

**Comment by miraclesu** [comment]
1. 修改任务分组，如果修改后的任务分组有更改任务结点的情况，那么，被删除的结点上会显示任务被删除
2. 现在任务添加和任务更新都是打印 `added` 日志

**Comment by melpozhang** [comment]
测试下来 是不更改任务节点,只修改分组也会导致节点上删除该任务,必须重新点开 保存一次才会添加

**Comment by miraclesu** [comment]
能否提供一下详细的操作步骤？如果能提供测试数据就更好了

**Comment by melpozhang** [comment]
1.创建新任务,分组为default,节点任意一个即可,看到node控制台打印added信息
2.编辑该任务,修改分组为test,node控制台打印deleted信息,此时任务已无法执行
3.在任务界面找到该任务,编辑,不做修改,直接保存,node控制台打印added

**Comment by miraclesu** [comment]
1. `default` 分组 -> `test` 分组，你指的 `node` 控制台是指在 `default` 分组里的节点吗？假设这个结点是 `A`。
2. `default` 和 `test` 这两个分组里都包含有结点 `A` 吗？除了结点 `A`，还有其他结点吗？
3. 测试了一下，我的 `default` 分组里有 `A` 结点，`test` 分组里有 `A & B` 两个结点，修改了任务的分组，由 `default` -> `test`，在 `A` 的日志里没有看到有任务的增删。

**Comment by melpozhang** [comment]
不是很懂你说的,分组关联的看上去是job和rule,和节点没有必然的关系,
2017-06-13T14:44:12.613+0800	INFO	log/log.go:26	job[36ce6194] rule[33ce6194] timer[0 */3 * * * *] has added
2017-06-13T14:44:20.093+0800	INFO	log/log.go:26	job[36ce6194] rule[33ce6194] timer[0 */3 * * * *] has deleted
然后从这个信息来看是,在我从default->test的时候delete了对应的rule

**Comment by miraclesu** [comment]
1. 从你给出的信息，无法定位你说的问题
2. 我的操作如图，把任务的分组从 `default` 改为 `test`
3. 在结点 `192.168.10.233` 的日志里，没有看到任务更新的日志，任务还是和之前一样在跑着

![group](https://user-images.githubusercontent.com/682907/27069663-6c6bb6c2-5048-11e7-8008-e5a2ec122cdd.png)
![default](https://user-images.githubusercontent.com/682907/27069664-6ccc2a48-5048-11e7-8fdc-0471666b0b20.png)

**Comment by miraclesu** [comment]
1. 任务 `job` 的定义为要做什么事情
2. `rule` 的定义是在哪里，什么时候做事情
3. 在 `cron` 里的任务其实是 `rule` 的时间，结点，做 `job` 定义的事情
4. `job` 的增删日志是对单个 `rule` 而言的

**Comment by melpozhang** [comment]
不是...我指的是任务的分组,而不是节点的分组,我就测试的单个节点,只是把任务分了default和test,然后修改时候修改的是上面的任务分组,
![image](https://user-images.githubusercontent.com/16367781/27069901-553fb222-5049-11e7-89de-712aec62e9fc.png)

**Comment by melpozhang** [comment]
节点的分组因为考虑到我们这的场景,还没有应用,主要是在测试任务分组

**Comment by miraclesu** [comment]
不好意思，我看成结点分组了，刚才测试了一下，确实存在这个问题，我找一下原因

**Comment by melpozhang** [comment]
没事哈 隔着屏幕确实沟通会存在点问题, 我也在看源码找这个问题,因为cronsun还是符合我们目前的一个需求,希望有问题能多多指教

**Comment by miraclesu** [comment]
最新的代码修复这个问题了，你可以试一下

**Comment by melpozhang** [comment]
解决了.看了下代码,是之前web端更新job的逻辑有问题吧,另外求教下代码里link是做什么用的

**Comment by miraclesu** [comment]
https://github.com/shunfei/cronsun/blob/master/node/group.go#L15

当结点分组有变动时，结点分组里的 `job` 需要更新，`link` 的作用是尽快找到需要更新的 `job` 列表
