### ISSUE TITLE
任务执行过程中修改任务导致并行数不生效

### ISSUE THREAD

**Issue by xuyi** [shunfei/cronsun#17]
Please answer these questions before submitting your issue. Thanks!
在你提交 issue 前，请先回答以下问题，谢谢！

1. What version of Go and cronsun version are you using?
你用的是哪个版本的 Go 和 哪个版本的 cronsun？
go1.8.1

2. What operating system and processor architecture are you using (`go env`)?
你用的是哪个操作系统，什么架构的？
linux x64

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
你做了什么，遇到了什么问题？尽可能描述清楚问题，最好把操作步骤写下来，按这些步骤操作后能重现你的问题。
任务执行过程中，修改任务会导致并行数不会生效。
modJob后没有更新count，后面又触发defer c.Job.unlimit()

4. What did you expect to see?
你期望得到什么样的结果？
modJob时更新count

5. What did you see instead?
现在你得到的结果是什么样的？

**Comment by miraclesu** [comment]
1. 执行的任务有什么特征？每次执行时长是多少，隔多少时间运行一次？并行数是多少？
2. 任务运行的过程中，修改了任务的哪些属性？
3. 没有明白你说的更新 `count` 是什么意思。

**Comment by xuyi** [comment]
比如设置一个任务  每10s跑一次，任务实际执行15s，并行数设置设置为1， 如果在上个任务还没有结束时修改了任务触发更新，会导致并行数的限制不会生效
更新count是指在Job的count数在modJob时没有继承过来

**Comment by miraclesu** [comment]
可以了，你用最新的代码试一下

**Comment by xuyi** [comment]
最新的代码可以了
