### ISSUE TITLE
etcd@v3.3.9+incompatible: checksum mismatch

### ISSUE THREAD

**Issue by kasheemlew** [shunfei/cronsun#177]
Please answer these questions before submitting your issue. Thanks!
在你提交 issue 前，请先回答以下问题，谢谢！

1. What version of Go and cronsun version are you using?
你用的是哪个版本的 Go 和 哪个版本的 cronsun？

Go: 1.15
cronsun: master commit 6b8ba934a9db86ac7ba832e00cfe3d897e3a43f0

2. What operating system and processor architecture are you using (`go env`)?
你用的是哪个操作系统，什么架构的？
Windows10 x64-based PC 

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
你做了什么，遇到了什么问题？尽可能描述清楚问题，最好把操作步骤写下来，按这些步骤操作后能重现你的问题。

```sh
$ git clone https://github.com/shunfei/cronsun.git
$ cd cronsum
$ go mod download
```

4. What did you expect to see?
你期望得到什么样的结果？

正常安装依赖

5. What did you see instead?
现在你得到的结果是什么样的？

```
verifying github.com/coreos/etcd@v3.3.9+incompatible: checksum mismatch 
        downloaded: h1:iKSVPXGNGqroBx4+RmUXv8emeU7y+ucRZSzTYgzLZwM=     
        go.sum:     h1:/pWnp1yEff0z+vBEOBFLZZ22Ux5xoVozEe7X0VFyRNo=     

SECURITY ERROR
This download does NOT match an earlier download recorded in go.sum.    
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

For more information, see 'go help module-auth'.
```

**Comment by kobeng** [comment]
删除本地这个文件：go.sum
