### ISSUE TITLE
ERROR	log/log.go:38	failed to fetch key[/cronsun/node/] from etcd: context deadline exceeded

### ISSUE THREAD

**Issue by mm333444** [shunfei/cronsun#2]
golang版本为1.8
提示这个错误,请问如何解决阿？

**Comment by miraclesu** [comment]
可能是任务结点机器与 `etcd` 机器之间的网络不好，造成了读取超时。
可以尝试加大超时时间配置：
`base.json` 里的
```
    "#ReqTimeout": "etcd 请求超时时间，单位秒",
    "ReqTimeout": 2,
```

**Comment by Leon2012** [comment]
这是因为默认的ETCD端口设错了，默认是http://127.0.0.1:2389应该改成http://127.0.0.1:2379

**Comment by mm333444** [comment]
@Leon2012 谢谢，确实是端口错了, 当时没注意..
