### ISSUE TITLE
shunfei 你好，我们想将cronsun用于线上，但是有一些问题？（计划任务）

### ISSUE THREAD

**Issue by bravewind** [shunfei/cronsun#20]
Please answer these questions before submitting your issue. Thanks!
在你提交 issue 前，请先回答以下问题，谢谢！

1. What version of Go and cronsun version are you using?
你用的是哪个版本的 Go 和 哪个版本的 cronsun？
采用的v0.1.0   （直接用的编译后的，所以没有安装go环境）
2. What operating system and processor architecture are you using (`go env`)?
你用的是哪个操作系统，什么架构的？
centos6.8 x86_64的架构

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
你做了什么，遇到了什么问题？尽可能描述清楚问题，最好把操作步骤写下来，按这些步骤操作后能重现你的问题。
我想按照crontab那样去执行我的任务，比如设置 * * */1 * * * 每一小时执行一次，但是失败了：

任务名称	运行节点	执行用户	执行时间	运行结果
relaxedsmille-catchOrder	192.168.201.111		07-05 17:35:00 ~ 07-05 17:35:02，于 192.168.201.111 耗时 2 秒 374 毫秒	成功 | 
relaxedsmille-catchOrder	192.168.201.111		07-05 17:34:00 ~ 07-05 17:34:02，于 192.168.201.111 耗时 2 秒 632 毫秒	成功 | 
relaxedsmille-catchOrder	192.168.201.111		07-05 17:33:00 ~ 07-05 17:33:03，于 192.168.201.111 耗时 3 秒 77 毫秒

4. What did you expect to see?
你期望得到什么样的结果？
自己控制任务执行的时间点

5. What did you see instead?
现在你得到的结果是什么样的？
不受控制，差不多3秒执行一次

**Comment by miraclesu** [comment]
1. `cronsun` 的执行时间规则与 `crontab` 一样，多了一个秒级支持，<秒> <分钟> <小时> <日> <月份> <星期>
2. 一个小时执行一次的时间规则应为：`0 0 */1 * * * `

**Comment by bravewind** [comment]
谢谢@miraclesu，我的规则写错了(* * 0/1 * * *)
