### ISSUE TITLE
界面缺少功能

### ISSUE THREAD

**Issue by navyaijm2017** [shunfei/cronsun#24]
1、go version go1.8.1
2、安装方法：
go get -u github.com/shunfei/cronsun
cd $GOPATH/src/github.com/shunfei/cronsun
sh build.sh
3、按照官方文档启动
4、访问：ip:7079/ui/ 只有crontsun这个tab页，dashboard、Log、Job、Node这4个table页都没有，这个是啥原因呢，MongoDB和etcd服务都正常

**Comment by luooo** [comment]
我这边也是这个问题

**Comment by navyaijm2017** [comment]
这个bug解决了嘛

**Comment by Doflatango** [comment]
刚更新了，可以拉下最新的 develop 分支看看

**Comment by navyaijm2017** [comment]
go get -u github.com/shunfei/cronsun
cd $GOPATH/src/github.com/shunfei/cronsun
sh build.sh

我这样编译，启动后还是一样呢

**Comment by Doflatango** [comment]
@navyaijm2017 切换到 develop 分支了吗，更新还没有合并到 master

**Comment by navyaijm2017** [comment]
@Doflatango 感谢，develop的正常。
