### ISSUE TITLE
FrontEnd load error

### ISSUE THREAD

**Issue by swift1911** [shunfei/cronsun#26]
Please answer these questions before submitting your issue. Thanks!
在你提交 issue 前，请先回答以下问题，谢谢！

1. What version of Go and cronsun version are you using?
你用的是哪个版本的 Go 和 哪个版本的 cronsun？
0.1.1 Golang 1.8
2. What operating system and processor architecture are you using (`go env`)?
你用的是哪个操作系统，什么架构的？
OS X 10.12.5
Chrome Version 60.0.3112.78 (Official Build) (64-bit)

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
你做了什么，遇到了什么问题？尽可能描述清楚问题，最好把操作步骤写下来，按这些步骤操作后能重现你的问题。

UI页面打不开

4. What did you expect to see?
你期望得到什么样的结果？
打开页面

5. What did you see instead?
现在你得到的结果是什么样的？
打不开页面

报错信息
TypeError: Cannot read property 'dashboard' of undefined
    at a.r [as $L] (language.js:35)
    at a.render (App.vue?fa19:20)
    at a.e._render (vue.common.js:3905)
    at a.o (vue.common.js:2441)
    at _r.get (vue.common.js:2780)
    at new _r (vue.common.js:2763)
    at ve (vue.common.js:2445)
    at a.gt.$mount (vue.common.js:7573)
    at a.gt.$mount (vue.common.js:9672)
    at init (vue.common.js:3360)

![image](https://user-images.githubusercontent.com/9301003/28706143-83788428-73a5-11e7-8595-70908832e8b8.png)

**Comment by Doflatango** [comment]
你给都信息太少了，复现不了你描述的问题。
建议用最新的版本试试。

**Comment by Doflatango** [comment]
@swift1911 这个问题可能跟语言环境有关，应该修复了 3eb91e0424cb08946de7e0641a69eca81931c53b

**Comment by swift1911** [comment]
我打个包来验证一下吗

**Comment by Doflatango** [comment]
如果你能帮忙测试一下也是极好的 :-)
