### ISSUE TITLE
centos5.5启动node报错

### ISSUE THREAD

**Issue by wudigailun** [shunfei/cronsun#27]
作者你好:
我在使用cronsun最新版，管理端已经成功部署，node端centos6没问题

在centos5.5启动cronnode报错

./cronnode  -conf conf/base.json 
2017-08-08T12:54:06.273+0800    ERROR   node/server.go:36       Init Config failed: function not implemented
go.uber.org/zap.Stack
        /home/miracle/go/src/go.uber.org/zap/field.go:190
go.uber.org/zap.(*Logger).check
        /home/miracle/go/src/go.uber.org/zap/logger.go:273
go.uber.org/zap.(*Logger).Check
        /home/miracle/go/src/go.uber.org/zap/logger.go:146
go.uber.org/zap.(*SugaredLogger).log
        /home/miracle/go/src/go.uber.org/zap/sugar.go:224
go.uber.org/zap.(*SugaredLogger).Errorf
        /home/miracle/go/src/go.uber.org/zap/sugar.go:139
github.com/shunfei/cronsun/log.Errorf
        /home/miracle/go/src/github.com/shunfei/cronsun/log/log.go:39
main.main
        /home/miracle/go/src/github.com/shunfei/cronsun/bin/node/server.go:36

不知道是什么原因，请帮忙看下，谢谢了。
conf/db.json
conf/etcd.json
2个文件已经配置成功。
centos6.x启动没问题的，有些node端是centos5.5，出现的这个错误。

**Comment by QLeelulu** [comment]
centos5.5 是 64位还是32位的系统 ？

**Comment by wudigailun** [comment]
生产环境centos5.5   64位的。昨天一技术群的朋友跟我说，cronsun要求是内核版本2.1.27以上，不知道是不是，我也不懂go语言，看不懂源码。centos6，反正都可以。

**Comment by QLeelulu** [comment]
哦，对的，是go对内核版本有要求。

**Comment by wudigailun** [comment]
好的，谢谢你了。
还有个问题
写定时任务，在cronsun里面是不是不支持命令行这样写？
/bin/bash  /scriptes/test.sh  >>/tmp/test.log

**Comment by miraclesu** [comment]
1.  系统要求

Operating system | Architectures | Notes
-- | -- | --
Linux 2.6.23 or later with glibc | amd64, 386, arm, s390x, ppc64le | CentOS/RHEL 5.x not supported

2. 定时任务里不支持管道命令，也不支持重定向

**Comment by wudigailun** [comment]
谢谢作者的回复
后续，会增加 重定向功能吗？而且，我发现这个命令行对空格的要求很严谨，比如
/bin/bash2个空格/test/hello.sh
这样都会报错。
挺不错的 平台，希望作者，后续经常更新下，我也测试了cronhub，基本已经没有更新了，该平台如果后续继续更新，我想用的人肯定会更多。

**Comment by miraclesu** [comment]
1. 空格的问题下个版本处理一下
2. 管道和重定向先考虑一下，如果要支持，也只在不开启安全选项里支持

**Comment by wudigailun** [comment]
恩，谢谢，我觉得，在生产环境中，定时任务，有很多时候，是需要把脚本结果追加到log的，写在脚本里面不是很方便，所以直接写在crontab里面。
还有在定时任务中，cronsun，执行定时任务的日志，是存放在mongodb中的吗？任务是存放在etcd下吗？

**Comment by QLeelulu** [comment]
> 还有在定时任务中，cronsun，执行定时任务的日志，是存放在mongodb中的吗？任务是存放在etcd下吗？

是的
