### ISSUE TITLE
cronsun---web界面，任务执行结果有乱码

### ISSUE THREAD

**Issue by wudigailun** [shunfei/cronsun#28]
你好，作者，我在 cronsun  web界面里面，Log普通用户执行任务，成功了，但是执行结果里面是乱码。
centos 6.6 系统

log用户是 以下字符集。
---->locale
LANG=zh_CN.UTF-8
LC_CTYPE="zh_CN.UTF-8"
LC_NUMERIC="zh_CN.UTF-8"
LC_TIME="zh_CN.UTF-8"
LC_COLLATE="zh_CN.UTF-8"
LC_MONETARY="zh_CN.UTF-8"
LC_MESSAGES="zh_CN.UTF-8"
LC_PAPER="zh_CN.UTF-8"
LC_NAME="zh_CN.UTF-8"
LC_ADDRESS="zh_CN.UTF-8"
LC_TELEPHONE="zh_CN.UTF-8"
LC_MEASUREMENT="zh_CN.UTF-8"
LC_IDENTIFICATION="zh_CN.UTF-8"
LC_ALL=zh_CN.UTF-8

root用户是是以下字符集：
locale
LANG=zh_CN.GB18030
LC_CTYPE="zh_CN.GB18030"
LC_NUMERIC="zh_CN.GB18030"
LC_TIME="zh_CN.GB18030"
LC_COLLATE="zh_CN.GB18030"
LC_MONETARY="zh_CN.GB18030"
LC_MESSAGES="zh_CN.GB18030"
LC_PAPER="zh_CN.GB18030"
LC_NAME="zh_CN.GB18030"
LC_ADDRESS="zh_CN.GB18030"
LC_TELEPHONE="zh_CN.GB18030"
LC_MEASUREMENT="zh_CN.GB18030"
LC_IDENTIFICATION="zh_CN.GB18030"

cronsun执行成功结果，有这种乱码
2017�� 08�� 22�� ���ڶ� 11:45:01 CST

我如何来更改这些问题？

**Comment by miraclesu** [comment]
1. 给出的 locale 机器是部署 node 结点的机器吗？
2. 看一下部署 web 结点的机器 locale 是什么？不清楚你的部署，这两者之间不一致，可能是造成问题的原因，log LANG=zh_CN.UTF-8, root LANG=zh_CN.GB18030，具体你排查一下。
3. 可以尝试在浏览器看一下当前编码是什么，如果不是 utf8，那基本可以判断是显示的问题，也就是浏览器编码和服务器的编码不一致。

**Comment by wudigailun** [comment]
这个locale是  node 节点的，我看了下，貌似是脚本里面指定了编码，已经忽略了，谢谢你。
