### ISSUE TITLE
UI出现404

### ISSUE THREAD

**Issue by warren22** [shunfei/cronsun#29]
按要求部署完毕，出现404.进不了WEB

**Comment by warren22** [comment]
按照使用说明部署，UI运行不起来。

**Comment by warren22** [comment]
我是服务器远程部署，跟这个没关系吧

**Comment by Doflatango** [comment]
@warren22 默认 UI 目录配置路径是相对的，应该是从启动路径那里找不到相对目录了，你可以先在`web.json` 把 `UIDir` 改成绝对路径。
后面打算静态文件打包进二进制文件里面就不用配置这个了

**Comment by KidoPlay** [comment]
绝对路径也是404.
测试的时候给了个路径
"UIDir": "/root/cronsun/cronsun-v0.2/ui",
这样依旧404

**Comment by Doflatango** [comment]
浏览器访问地址是 http://xxx/ui/,  `ui` 后面跟着`/`

另外，你可以切到 `develop` 分支，更新到最新的代码，已经不需要 `UIDir` 配置了

**Comment by warren22** [comment]
OK了，
