### ISSUE TITLE
请问一下web ui 调度器挂了整个服务都会挂了？

### ISSUE THREAD

**Issue by Someant** [shunfei/cronsun#30]
Please answer these questions before submitting your issue. Thanks!
在你提交 issue 前，请先回答以下问题，谢谢！

1. What version of Go and cronsun version are you using?
你用的是哪个版本的 Go 和 哪个版本的 cronsun？
答：Go 1.8.3 暂未使用cronsun
2. What operating system and processor architecture are you using (`go env`)?
你用的是哪个操作系统，什么架构的？
答：Cetnos amd64

从架构图上来看，当web ui和调度器是单节点的，当调度器挂了，定时任务就无法被触发，还是说我理解有误？请问一下，目前的架构是否支持分布式的调度器，或者说用重新选举的方式，其中一个node会成为新的调度器？

**Comment by Doflatango** [comment]
web 节点是独立的，挂了不会影响系统，重启即可。
具体任务执行的节点，如果挂了（一般单台服务器会有一个执行节点），会影响到相关任务的执行，不会导致整个系统挂了，你也可以做个监控，随时重启就行。

**Comment by wudigailun** [comment]
etcd可以做集群吧，etcd是存储任务的。。比如我这台 cronsun master端服务器挂了，我如何用备用的机器，来继续提供服务，有没有这种方案？

**Comment by Someant** [comment]
上面其实和我想的类似，这种模式依赖于主调度器，单主调度器挂机了之后，之后的定时任务将不会再触发了，从而影响了业务。

**Comment by wudigailun** [comment]
作者很忙，其实这个平台可以做成一个很有搞头的开源项目，冗余的、备份的，支持更多的。哈哈哈。我们生产已经在使用了，目前上了2台，只是我们的业务机器，因为时间很长，大多都是 centos5.x系统，并不支持该 node安装，我前边的问题，作者也给了很明确的答复，对内核有要求。新的项目后续，都要放到这个平台来运行，目前，我担心的，就是单点问题，希望作者可以指导一个方案出来，cronsun，我监控都做了。基于 url的和port的，但是如果 机器 down了。没有及时修复，肯定是会带来影响的。

**Comment by QLeelulu** [comment]
> etcd可以做集群吧，etcd是存储任务的。。比如我这台 cronsun master端服务器挂了，我如何用备用的机器，来继续提供服务，有没有这种方案？

你说的这些cronsun是都支持的。

1. etcd一般部署5个节点（如果你希望高可用的话）
2. cronsun的任务类型选择“单机单进程”（同一时间只有一个任务进程在某个节点上面执行），然后执行节点选择多个，在执行任务的时候就会从多个节点中挑选一个可用的节点来执行；

**Comment by wudigailun** [comment]
恩，我也是这么理解的。
作者，请问，cronsun里面执行任务，他通过什么判断的一个任务返回，成功 or 失败的？
我有些定时任务，执行脚本后，页面显示成功，但是点击成功看，下边有报错，比如缺少什么模块之类的，这样给我带来困惑。我还得一个一个去查看成功的任务是否有报错存在。。

**Comment by Doflatango** [comment]
cronsun 以任务进程退出时的状态来作为判断成功或失败的依据，不关心具体任务逻辑，更不知道跑得什么业务，所以这个结果只是表示任务进程跑了没，进程执行得怎么样，实际的任务逻辑往往会关联的复杂的业务逻辑，成功与否不能一刀断。

**Comment by Someant** [comment]
@QLeelulu 你这种形式还是依赖于一个触发器吧？你这样做只能保证已经触发的任务必定会执行，而不能保证后续的任务会被触发。

**Comment by wudigailun** [comment]
cronsun 以任务进程退出时的状态来作为判断成功或失败的依据，类似
echo  $?  这样吗?

**Comment by QLeelulu** [comment]
@Someant 任务都保存在etcd，只要保证etcd集群正常则整个cronsun系统就是正常的。

@wudigailun 如果是用shell脚本里面调用了其他的命令，则可以使用以下的写法：

```
#!/usr/bin/bash

/data/www/sh/cron/test-cron # 你的任务命令
recturncode=$? # 返回结果
echo $recturncode
exit $recturncode
```

**Comment by wudigailun** [comment]
@作者，这个我知道，说直白点，这个成功 or  失败，只执行完脚本之后
echo   $?  的返回值，来决定的吧？

**Comment by Doflatango** [comment]
@wudigailun 不是 echo，是退出时的状态码，只有等于 0 时是认为成功的。
> exit 0

**Comment by wudigailun** [comment]
了解。哈哈，运维，习惯了。echo $?，意思我懂了，谢谢作者。

**Comment by wudigailun** [comment]
作者，你好，为了避免单点，目前在测试etcd集群搭建，采用了3台不同机器，我有2个问题：
1、目前我采用  etc单点，etcd配置文件
    "Endpoints":[
        "http://172.16.1.220:2379"
    ],
    "Username":"",
    "Password":"",
    "#DialTimeout":"单位秒",
    "DialTimeout": 2
问题：如果我配置了3个  etcd机器 的话。这里  http 地址需要写3个吗？还是其他配置？

2、如上边你回答所说，如果我采用了 多个etcd机器的话，我所有的 定时任务，就必须得更改为 单任务单进程方式，执行任务，对吧？

**Comment by miraclesu** [comment]
1. 地址写 3 个
2. 如果你的任务不允许单点失败(也就是一个结点挂了，任务就不能执行了)，那需要改成单机单进程，这个和采用多少个 etcd 没关系。如果只是普通的 crontab 任务，那保留原来的普通任务类型就好。

**Comment by wudigailun** [comment]
谢谢你的回答。
我目前就是普通的crontab任务。
我自己的理解是，比如我现在有3个etcd服务器，我在平台添加一个任务后，他应该是把任务都会同步到3台etcd服务器上，但是只有一个   选举的那台，来执行 任务，对吧？
不好意思，我还是不怎么明白，单点失败？指的是什么。。这个单机单进程没懂什么意思。。

**Comment by miraclesu** [comment]
比如你有一个任务，是每 10 分钟调用机器 A 上的一个接口，这个接口只能每 10 分钟调用一次(比如扣费的，每 10 分钟扣 0.1 元)。
如果你把这个任务设置为普通任务，让他在机器 B 上执行，如果机器 B 挂了，是不是机器 A 上的接口就不会被调用了，那扣费就不正常了。
如果这个任务设置成单机单进程任务，选择机器 B、C、D...，那么 cronsun 会每 10 分钟选择一台机器执行这个任务，除非所有机器都挂了，否则这个任务就会每 10 分钟正常执行一次。

**Comment by miraclesu** [comment]
etcd 的主要作用是存储任务，执行任务是部署了 cronnode 的机器，和部署 etcd 的机器没有直接的关系。

**Comment by wudigailun** [comment]
哦。我们没有这种需求，都是自己机器处理自己机器上边的业务，即使有比如，A机器，每1小时，往B机器同步一个文件。比如B机器挂了。但是平台把A任务发送过去脚本执行了。执行成功不成功，是A机器的事情啊。

**Comment by wudigailun** [comment]
恩对，etcd是存储任务，mongodb存储日志，最终是cronnode调用etcd里面的任务？我对我而言，etcd是主要的。因为我在另一个帖子问过了。如何删除 cronsun平台上边 无效的主机，告诉我是在mongodb上做remove IP操作，我任务，主机ip是保存在 mongodb上边的吗？如果我想实现集群化的话。是不是etcd和mongdob都需要做成集群？？？如果mongodb单台的话，挂了。会影响node端执行任务吗？这个是我担心的。

**Comment by miraclesu** [comment]
如果机器 A 是一个分布式系统，那这个系统就会正常工作，任务调度是 cronsun 做的。

你理解普通任务和单机单进程任务的区别就好，需要用的时候试一下就可以了。

**Comment by miraclesu** [comment]
1. etcd 需要部署成集群的，否则 etcd 挂了，cronnode 里只有普通任务能正常执行，不过整个系统很多功能都用不了。
2. mongodb 最好做成集群的，否则 mongo 挂了，虽然不影响任务的执行，但是界面用不了，执行结果也查看不了。

**Comment by wudigailun** [comment]
好的，我先消化下。赶紧更新版本啊，作者 ^-^，期待。

**Comment by wudigailun** [comment]
对了，作者，etcd，针对cronsun来说，做成静态配置就可以满足了吧。

**Comment by miraclesu** [comment]
没有明白你说的静态配置是什么意思。

**Comment by wudigailun** [comment]
我对etcd不是很了解。刚接触，我看有三种模式，静态配置， etcd发现，dns发现。没事了，我自己研究下吧。谢谢了作者。

**Comment by maomaosan2008** [comment]
> 我对etcd不是很了解。刚接触，我看有三种模式，静态配置， etcd发现，dns发现。没事了，我自己研究下吧。谢谢了作者。

hello，我这边也最早也是用etcd集群模式，在etcd.json中添加了三个IP地址，但在执行任务的时候有些节点一直不执行，集群状态也是健康的，改为单点etcd就没问题，有什么解决思路吗
