### ISSUE TITLE
在平台去除一台机器

### ISSUE THREAD

**Issue by wudigailun** [shunfei/cronsun#32]
作者你好：我又来提问来了。
我以前添加了一台机器，现在因为换了IP地址，在cronsun平台，显示故障机，这个很正常，因为进程没有启动，IP地址也换了。我想在cronsun平台删除这台故障机显示，如何操作呢？

**Comment by miraclesu** [comment]
离线机器/故障机器的功能还没有做，如果你想手动删除，可以直接从数据库删掉(如果错误操作删错了，重启了一下删错的结点，就会有新记录了，不用担心)：
```
db.node.find({_id:"192.168.1.110"})
db.node.remove({_id:"192.168.1.110"})
```

**Comment by wudigailun** [comment]
好的，谢谢。
