### ISSUE TITLE
执行脚本好像不支持填写参数，不知道后面是否会支持？

### ISSUE THREAD

**Issue by jagerzhang** [shunfei/cronsun#34]
部署试用了一下cronsun，非常喜欢这个区中心化的概念。
使用过程中发现生产环境有一些暂时不满足的需求，这里简单说下，看看作者是否有兴趣TO DO。
1、cronsun 只能执行脚本，而且不支持参数
我们这边现网很多已经有了现成的脚本，大部分都需要带入一个参数，以便于脚本的多种场景复用，比如我们这边大量用到一种自拉起脚本，比如拉起filebeat
```
/data/checkprocess.sh  filebeat  
```
这个脚本还可以拉起其他程序，因此是一个共用的功能脚本，要应用到cronsun就只能再包一层脚本来执行了。现网还有一些curl调用的任务，目前是直接写到crontab的（当然， 这个本身是不推荐的）

个人建议：既然只能是纯脚本，cronsun能否在前台直接集成一个脚本管理模块？可以在前台直接管理脚本，方便编辑？若觉得这个方案集成太重，是否可以支持下脚本参数？

**Comment by wudigailun** [comment]
lz好，针对你的问题，我也遇到了。目前是不支持的。只支持普通的
/bin/bash  /scripts/test.sh  这种写法，如果你想传参进去。你可以把传参后的执行命令在写一个脚本，然后cronsun平台 运行新脚本。比如：
cat  newtest.sh
/bin/bash  /data/checkprocess.sh  filebeat 

cronsun平台，去执行newtest.sh即可。不过麻烦点，可以应急使用。我们生产也有cd 到一个目录，执行脚本的。。这种，crontab可以。cronsun不行。然后把命令写到一个新脚本。解决了。前提是，不经常变动的脚本。

**Comment by jagerzhang** [comment]
嗯，和我上面说的一样，现在就是要包一层脚本来调用了，问题确实不大。要是能支持那也就更加完美了~

**Comment by wudigailun** [comment]
恩对，我已经和作者提过这个问题了，其实我觉得，这个平台要是有时间去开发，是一个很不错的项目。

**Comment by jagerzhang** [comment]
我在关闭的issue里面看到有不少人有这个诉求，不过作者出于安全等方面考虑暂不打算支持这个参数或命令填写。
现在作者推荐的做法是将脚本先包好，然后一起推送到node服务器，再添加任务计划。
既然已经有通信通道了，是不是可以直接从中心把这些脚本管理起来，可以直接推送到node，那就非常方便了。
不过这个有点类似于我目前在做的自动化运维平台了，估计会觉得设计有点重。。。

**Comment by wudigailun** [comment]
恩对。你etcd是集群还是单点？我现在遇到了一个问题，你可以看下我刚刚发的那个 issue，可以帮忙解决下吗？

**Comment by jagerzhang** [comment]
我今天刚接触cronsun，所以只部署了2个点，就一套etcd，我可能还没有你熟悉。。之前一直在测试gocron这个中心化任务管理的，不过我们服务器太多了，所以gocron作者推荐我试用下这个来的。。

**Comment by wudigailun** [comment]
恩，我建议你，如果是生产的话，直接做成集群的。已经有数据的etcd，单点，在做成集群，不知道如何来实现。我目前还在测试。

**Comment by QLeelulu** [comment]
参数支持应该可以加，应该不涉及到安全性问题。 @miraclesu

**Comment by jagerzhang** [comment]
支持参数的优化不知道有什么进展么~~我这边打算大批量上现网使用了~~

**Comment by Doflatango** [comment]
@jagerzhang 现在是支持参数，但只是简单的按空格来分割参数，所以如果参数带有空格的话现在不支持，对于空格转义这些，包括其它的问题，最近会抽一些时间来集中处理一下。

**Comment by jagerzhang** [comment]
给力，实际也是只有简单空格区分的参数需求。
