### ISSUE TITLE
可能是bug

### ISSUE THREAD

**Issue by towerjt** [shunfei/cronsun#36]
node.go中的ISNodeFault
`
func ISNodeFault(id string) (bool, error) {
	n := 0
	err := mgoDB.WithC(Coll_Node, func(c *mgo.Collection) error {
		var e error
		n, e = c.Find(bson.M{"_id": id, "alived": true}).Count()
		return e
	})

	return n > 0, err
}
`
如果返回true的话，实际上是节点有效，跟函数的命名是相反的吧？

是不是应该改成：
`
return n == 0, err
`

**Comment by miraclesu** [comment]
这个函数命名和逻辑是反了，但在使用那边也是反的
下一版把这个处理一下，谢谢反馈
