### ISSUE TITLE
反馈一个登录BUG

### ISSUE THREAD

**Issue by jagerzhang** [shunfei/cronsun#37]
使用最新版cronsun，搭建好首次打开WEB提示需要登录，然后使用默认账号密码登录之后，这个登录态居然能一直保留，具体表现就是我使用浏览器无痕模式也不再需要登录了。。
换一台电脑也不再需要登录了，直接可以打开仪表盘和其他所有功能，那这个登录好像没什么意义了哈~~

**Comment by jagerzhang** [comment]
哦 看到介绍里面说，好像也只是首次打开需要登录。。。

**Comment by Doflatango** [comment]
在 `web.json` 文件有个配置项 `Auth.Enabled`， 默认为 `false` ，表示不需要登录验证。
你当时用的是默认值还是改了之后发生这个问题？

**Comment by tawateer** [comment]
我也遇到这个问题了：

![image](https://user-images.githubusercontent.com/4546313/32132003-f393f0da-bb80-11e7-9504-89f2b9838ec1.png)

Auth.Enabled 是 false，但是还是跳到登陆界面。

**Comment by Doflatango** [comment]
@tawateer 你这里是尝试获取会话的时候返回错误了（截图是 `Etcd` 连不上），导致强行跳到登录页面，跟一楼的描述看起来不像同一个问题。
