### ISSUE TITLE
节点 startProc 的作用是什么呢？

### ISSUE THREAD

**Issue by bay1ts** [shunfei/cronsun#38]
您好，看了本项目代码，对proc/startProc的作用不是很理解。希望可以描述一下他的工作。谢谢

**Comment by Doflatango** [comment]
假设你已经了解了 Etcd [lease](https://coreos.com/etcd/docs/latest/dev-guide/interacting_v3.html#grant-leases) 的概念和用法。

Cronsun 有个查看执行中的任务的功能，正在执行的任务会集中放在一个地方`A`，执行完就从`A`中把对应的任务移除。如果有一天节点突然不幸挂掉，此时任务可能刚好执行完但没来得及从`A`中移除，或者任务跟着节点一起挂了，当然任务信息也还在`A`，这样`A`中就有些任务一直冤魂不散，它们本应该跟着节点一起消失的。解决办法就是给这些任务信息加个 TTL，自动超时清掉就好了，如果你了解了 `lease` 的用法，看到这里你就明白那个函数是干嘛用的了，就是简单的维护了一个 `lease` 而已。  :-)
