### ISSUE TITLE
任务节点需要安装哪些服务？

### ISSUE THREAD

**Issue by station19** [shunfei/cronsun#39]
任务节点需要安装哪些服务？ MongoDB 和etcd? 都需要安装吗

**Comment by Doflatango** [comment]
不需要，`MongoDB` 和 `Etcd` 只是用来存储数据和通讯的。
每个需要跑任务的节点只需要运行一个 `cronnode` 进程，所有的 `cronnode` 进程使用同一 `MongoDB` 集群和 同一 `Etcd` 集群。

**Comment by station19** [comment]
客户端启动的时候需要修改哪些配置么?比如db.json 之类的

**Comment by station19** [comment]
![q](https://user-images.githubusercontent.com/4527618/31512095-60ee2db4-af4f-11e7-9107-49ccb3e71108.png)
在客户端 启动的时候总是报错,啥原因?服务端和客户端是分开的机器
