### ISSUE TITLE
It can't work with go 1.7.3

### ISSUE THREAD

**Issue by zhangchunsheng** [shunfei/cronsun#4]
It can't work with go 1.7.3, so I upgrade go to 1.7.4. Now it can work.

Require Go >= 1.7.4 not Go >= 1.7+

**Comment by miraclesu** [comment]
What error is output?
I tested on `go1.7.3`, everything is ok.

**Comment by zhangchunsheng** [comment]
segment fault when I run ./cronnode -conf conf/base.json on centos 6. I haven't log it. It build success, but It can't work. Anyway it can work on go 1.7.4.
