### ISSUE TITLE
job[/cronsun/cmd/default/a5fafb45] running on[192.168.12.137] running:[2] 这个错误是什么意思？

### ISSUE THREAD

**Issue by NSObjects** [shunfei/cronsun#43]
Please answer these questions before submitting your issue. Thanks!
在你提交 issue 前，请先回答以下问题，谢谢！

1. What version of Go and cronsun version are you using?
你用的是哪个版本的 Go 和 哪个版本的 cronsun？
cronsun-v0.2.1
2. What operating system and processor architecture are you using (`go env`)?
你用的是哪个操作系统，什么架构的？
ubuntu 16.4

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
你做了什么，遇到了什么问题？尽可能描述清楚问题，最好把操作步骤写下来，按这些步骤操作后能重现你的问题。
任务执行失败。我手动启动这个脚本又没出错。 
这个错误日志是什么意思？
job[/cronsun/cmd/default/a5fafb45] running on[192.168.12.137] running:[2]

4. What did you expect to see?
你期望得到什么样的结果？

5. What did you see instead?
现在你得到的结果是什么样的？

**Comment by QLeelulu** [comment]
贴下你的任务设置看看，应该是超过了你设定的同时允许执行的任务数

**Comment by NSObjects** [comment]
![a1f9fea7-b09d-46d3-8b26-c54f16796856](https://user-images.githubusercontent.com/17995427/31613031-6d6d9210-b2b4-11e7-86ab-94a7f34019bf.png)

**Comment by NSObjects** [comment]
我是不是不应该选择单机单进程。。。

**Comment by QLeelulu** [comment]
你选的这个`单机单进程`任务类型，如果上次执行的任务还没完成，下次定时到来的时候，发现上次的任务还没跑完，是不会执行新的任务的。

**Comment by NSObjects** [comment]
@QLeelulu 谢谢，我改好了。
