### ISSUE TITLE
有个节点启动不了，context deadline exceeded

### ISSUE THREAD

**Issue by NSObjects** [shunfei/cronsun#44]
go version go1.9 linux/amd64
cronsun最新版的
ubuntu 16.4

./cronnode -conf conf/base.json
2017-10-23T14:38:34.134+0800	ERROR	node/server.go:47	context deadline exceeded
go.uber.org/zap.Stack
	/home/miracle/go/src/go.uber.org/zap/field.go:190
go.uber.org/zap.(*Logger).check
	/home/miracle/go/src/go.uber.org/zap/logger.go:273
go.uber.org/zap.(*Logger).Check
	/home/miracle/go/src/go.uber.org/zap/logger.go:146
go.uber.org/zap.(*SugaredLogger).log
	/home/miracle/go/src/go.uber.org/zap/sugar.go:224
go.uber.org/zap.(*SugaredLogger).Errorf
	/home/miracle/go/src/go.uber.org/zap/sugar.go:139
github.com/shunfei/cronsun/log.Errorf
	/home/miracle/go/src/github.com/shunfei/cronsun/log/log.go:39
main.main
	/home/miracle/go/src/github.com/shunfei/cronsun/bin/node/server.go:47

**Comment by Doflatango** [comment]
检查下那个节点的 Etcd 配置是否正确以及是否可以连上 Etcd。

**Comment by NSObjects** [comment]
重启机器忘记重启etcd了。。 谢谢
