### ISSUE TITLE
关闭cronnode配置问题

### ISSUE THREAD

**Issue by wudigailun** [shunfei/cronsun#46]
作者，你好，我有一个问题。
当前环境，三台服务器，etcd和mongodb我都做了集群了。
cronweb，也把db etcd的配置文件，添加了三台机器的ip和端口。
我想问下，cronnode节点，需要修改  db 和 etcd 配置文件把。把三台机器的mongodb和etcd都添加进去?

**Comment by Doflatango** [comment]
对。简单的做法，不管 `cronweb` 节点还是 `cronnode` 节点，把所有配置文件拷贝过去，保持一样的配置。

**Comment by wudigailun** [comment]
@Doflatango  谢谢你的做法，我现在已经把cronsun，做成了，完完全全的高可用了。从web，到etcd，mongodb，如果有需要的，我乐意把方法发下。

**Comment by QLeelulu** [comment]
@wudigailun 要是能整理成详细的MD文档就更好了，那样我们可以直接放到wiki上了
