### ISSUE TITLE
编译安装出现 cannot find package

### ISSUE THREAD

**Issue by hanye1310370** [shunfei/cronsun#48]
我执行编译 shbuild.sh的时候 出现
build file to ./dist
bin/node/server.go:12:2: cannot find package "github.com/shunfei/cronsun" in any of:
	/root/go/src/github.com/shunfei/cronsun (from $GOROOT)
	($GOPATH not set. For more details see: 'go help gopath')
bin/node/server.go:13:2: cannot find package "github.com/shunfei/cronsun/conf" in any of:
	/root/go/src/github.com/shunfei/cronsun/conf (from $GOROOT)
	($GOPATH not set. For more details see: 'go help gopath')
bin/node/server.go:14:2: cannot find package "github.com/shunfei/cronsun/event" in any of:
	/root/go/src/github.com/shunfei/cronsun/event (from $GOROOT)
	($GOPATH not set. For more details see: 'go help gopath')
bin/node/server.go:15:2: cannot find package "github.com/shunfei/cronsun/log" in any of:
	/root/go/src/github.com/shunfei/cronsun/log (from $GOROOT)
	($GOPATH not set. For more details see: 'go help gopath')
bin/node/server.go:16:2: cannot find package "github.com/shunfei/cronsun/node" in any of:
	/root/go/src/github.com/shunfei/cronsun/node (from $GOROOT)
	($GOPATH not set. For more details see: 'go help gopath')
bin/node/server.go:9:2: cannot find package "go.uber.org/zap" in any of:
	/root/go/src/go.uber.org/zap (from $GOROOT)
	($GOPATH not set. For more details see: 'go help gopath')
bin/node/server.go:10:2: cannot find package "go.uber.org/zap/zapcore" in any of:
	/root/go/src/go.uber.org/zap/zapcore (from $GOROOT)
	($GOPATH not set. For more details see: 'go help gopath')
build fail.
我的go版本是
[root@centos cronsun-0.2.2]# go version
go version go1.9.2 linux/amd64

然后我是用cronsun-v0.2.2-linux-amd64.zip安装  登录提示404
![default](https://user-images.githubusercontent.com/12537321/33260130-e949a1c0-d399-11e7-9055-184f9b1f4128.png)

**Comment by Doflatango** [comment]
1. 自行编译使用 `feature/glide` 分支，另外 go get 的时候你需要翻墙才能顺利下载到所有包。
2. 你要访问的后台地址是: http://192.168.1.208:7079/ui/

**Comment by hanye1310370** [comment]
用的那个linux的tar包  也不行  没有web端的展示页面呀  访问404

**Comment by hanye1310370** [comment]
有没有编译好的 tar包  丢一份吧  十分感谢

**Comment by Doflatango** [comment]
启动 cronweb 后，你访问的地址是：http://127.0.0.1:7079/ui/ 这个吗（注意后面带着 `/ui/`）？

请从 [Release](https://github.com/shunfei/cronsun/releases/latest) 页面下载编译好的二进制文件

**Comment by hanye1310370** [comment]
![Uploading 图片.png…]()

**Comment by hanye1310370** [comment]
../cronnode -conf ../conf/base.json
 ../cronweb -conf ../conf/base.json
root@debian1:/data/cronsun-v0.2.2/node# curl  http://127.0.0.1:7079/ui
404 page not found

**Comment by hanye1310370** [comment]
使用的就是那个release下载的 第二个linux版本的

**Comment by hanye1310370** [comment]
我不清楚这个web的这个yemi

**Comment by hanye1310370** [comment]
没有找到这个web的页面展示位置  就是程序位置在哪里

**Comment by Doflatango** [comment]
结尾 `/ui/` 不是 `/ui`，你少写了一个 `/`。

**Comment by hanye1310370** [comment]
好的  谢谢了  万分感谢
