### ISSUE TITLE
*/1 * * * * * 会导致每秒执行一次脚本吗

### ISSUE THREAD

**Issue by littlespark** [shunfei/cronsun#5]
包: cronsun-v0.1-drawin-amd64.zip
配置:
![image](https://cloud.githubusercontent.com/assets/5679209/26362551/e0de5f7a-4010-11e7-847a-5f4baa34ccb2.png)
查看记录:
![image](https://cloud.githubusercontent.com/assets/5679209/26362575/f8a25288-4010-11e7-9d8e-8db08c7b9c29.png)

**Comment by miraclesu** [comment]
是的，你可以点那个 `？` 号看一下，规则和 `crontab`，但比 `crontab` 多支持了一个秒

**Comment by littlespark** [comment]
ok了,感谢
0 */1 * * * *    每隔1分钟执行一次
*/1 * * * * *     每隔1秒钟执行一次
