### ISSUE TITLE
账号系统可以增加一个观察者权限吗？

### ISSUE THREAD

**Issue by xiazhicheng** [shunfei/cronsun#52]
总感觉很轻易就能修改删除别人的任务，怕误操作。

**Comment by xiazhicheng** [comment]
0.2.3版本cronsun，linux64位，有centos和Ubuntu，部署了cronsun，感觉账号系统要是能增加一个观察者就好了，只能看任务，不能改任务，目前的管理员和开发者账号权限太高了，怕把别人的任务给改或者删了。

**Comment by Doflatango** [comment]
请升级到最新版本。
