### ISSUE TITLE
ubuntu下 cornsun 启动报错,包括server端和node端

### ISSUE THREAD

**Issue by leolee2356** [shunfei/cronsun#54]
软件版本: 使用的是二进制包,
系统版本:
Ubuntu 16.04.3 LTS

server端开始可以启动,
启动完了,点击页面后,报错如下
`root@LAPTOP-AAH6DN5C:~/etcd-v3.3.0-rc.0-linux-amd64/cronsun-v0.2.3# ./cronweb -conf conf/base.json
2017-12-27T17:39:53.811+0800    INFO    web/server.go:90        cronsun web server started on :7079, Ctrl+C or send kill sign to exit
2017-12-27T17:40:11.041+0800    ERROR   web/node.go:162 failed to fetch key[/cronsun/node/] from etcd: context deadline exceeded
github.com/shunfei/cronsun/log.Errorf
        /Users/Doflatango/go/src/github.com/shunfei/cronsun/log/log.go:39
github.com/shunfei/cronsun/web.(*Node).GetNodes
        /Users/Doflatango/go/src/github.com/shunfei/cronsun/web/node.go:162
github.com/shunfei/cronsun/web.(*Node).GetNodes-fm
        /Users/Doflatango/go/src/github.com/shunfei/cronsun/web/routers.go:86
github.com/shunfei/cronsun/web.BaseHandler.ServeHTTP
        /Users/Doflatango/go/src/github.com/shunfei/cronsun/web/base.go:139
github.com/shunfei/cronsun/web.(*BaseHandler).ServeHTTP
        <autogenerated>:1
github.com/shunfei/cronsun/vendor/github.com/gorilla/mux.(`
node 端压根就启动不了,报错如下:
`
root@LAPTOP-AAH6DN5C:~/etcd-v3.3.0-rc.0-linux-amd64/cronsun-v0.2.3# ./cronweb -conf conf/base.json
2017-12-27T17:39:53.811+0800    INFO    web/server.go:90        cronsun web server started on :7079, Ctrl+C or send kill sign to exit
2017-12-27T17:40:11.041+0800    ERROR   web/node.go:162 failed to fetch key[/cronsun/node/] from etcd: context deadline exceeded
github.com/shunfei/cronsun/log.Errorf
        /Users/Doflatango/go/src/github.com/shunfei/cronsun/log/log.go:39
github.com/shunfei/cronsun/web.(*Node).GetNodes
        /Users/Doflatango/go/src/github.com/shunfei/cronsun/web/node.go:162
github.com/shunfei/cronsun/web.(*Node).GetNodes-fm
        /Users/Doflatango/go/src/github.com/shunfei/cronsun/web/routers.go:86
github.com/shunfei/cronsun/web.BaseHandler.ServeHTTP
        /Users/Doflatango/go/src/github.com/shunfei/cronsun/web/base.go:139
github.com/shunfei/cronsun/web.(*BaseHandler).ServeHTTP
        <autogenerated>:1
github.com/shunfei/cronsun/vendor/github.com/gorilla/mux.(
`

**Comment by Doflatango** [comment]
连接 Etcd 超时了，检查下你的网络以及 Etcd 状态

**Comment by leolee2356** [comment]
确实是没有启动 ./etcd .启动后,单机测试通过
