### ISSUE TITLE
关于kille etcd和cronnode、cronweb之后，再启动任务丢失

### ISSUE THREAD

**Issue by mintbeer** [shunfei/cronsun#57]
反映一个问题，当我kille etcd和cronnode、cronweb之后，再启动任务丢失，无法从mongodb读出来。

**Comment by Doflatango** [comment]
任务信息是保存在 Etcd 上面的，MongoDB 是保存任务`日志`的。重启之后 Etcd 能连上吗？

**Comment by mintbeer** [comment]
能连上etcd，难道说kill掉etcd之后，会丢失数据？

**Comment by Doflatango** [comment]
你可以手动看看任务数据是否还在（host:port 替换成你 Etcd 的地址和端口）
```bash
ETCDCTL_API=3 ./etcdctl get /cronsun/cmd --prefix --endpoints="host:port"
```

**Comment by mintbeer** [comment]
我已经找到原因，是因为启动的时候需要恢复数据。谢谢你啦。
