### ISSUE TITLE
go get的时候报错

### ISSUE THREAD

**Issue by afu110** [shunfei/cronsun#59]
1. What version of Go and cronsun version are you using?
我用的go1.9，安装了etcd3.3.使用了最新的cronsun。用go get命令安装的

2. What operating system and processor architecture are you using (`go env`)?
操作系统为macos  架构为amd64

3. What did you do?
使用go get -u github.com/shunfei/cronsun命令安装报错,具体错误如下:
package github.com/coreos/etcd/mvcc/mvccpb: cannot find package "github.com/coreos/etcd/mvcc/mvccpb" in any of:
	/usr/local/go/src/github.com/coreos/etcd/mvcc/mvccpb (from $GOROOT)
	/Users/xxxx/Project/learngo/src/github.com/coreos/etcd/mvcc/mvccpb (from $GOPATH)

从报错看，是cronsun没找到etcd中的一个包，我自己上etcd的github上看确实也没有这个包，请帮忙看下什么问题呢？多谢

**Comment by Doflatango** [comment]
这个是依赖版本的问题，使用 feature/glide 分支来编译（[glide](https://glide.sh/)），或者直接从 [releases](https://github.com/shunfei/cronsun/releases) 页面下载二进制文件使用。
