### ISSUE TITLE
任务不按配置精确执行

### ISSUE THREAD

**Issue by dongchuant** [shunfei/cronsun#68]
cronsun release 0.2
CentOS release 6.2
单机单进程任务 每分钟执行 0 * * * * * 共三个节点
执行日志显示大部分是两分钟执行一次
请问遇到过这种情况吗？
![cronsun](https://user-images.githubusercontent.com/5419747/36893479-244a628e-1e43-11e8-91ce-8ed2ea0651bf.png)

**Comment by Doflatango** [comment]
这个问题应该修复了，但是还未发布版本。

**Comment by dongchuant** [comment]
感谢~ 我编译最新的代码 测试下
