### ISSUE TITLE
节点启动报错

### ISSUE THREAD

**Issue by melpozhang** [shunfei/cronsun#7]
2017-05-24T10:41:43.761+0800	ERROR	log/log.go:38	context deadline exceeded
go.uber.org/zap.Stack
	/home/golang/src/go.uber.org/zap/field.go:209
go.uber.org/zap.(*Logger).check
	/home/golang/src/go.uber.org/zap/logger.go:273
go.uber.org/zap.(*Logger).Check
	/home/golang/src/go.uber.org/zap/logger.go:146
go.uber.org/zap.(*SugaredLogger).log
	/home/golang/src/go.uber.org/zap/sugar.go:223
go.uber.org/zap.(*SugaredLogger).Errorf
	/home/golang/src/go.uber.org/zap/sugar.go:138
github.com/shunfei/cronsun/log.Errorf
	/home/golang/src/github.com/shunfei/cronsun/log/log.go:38
main.main
	/home/golang/src/github.com/shunfei/cronsun/bin/node/server.go:47
求问下这个context deadline exceeded是什么原因

**Comment by miraclesu** [comment]
#2

**Comment by miraclesu** [comment]
参考 #2

**Comment by melpozhang** [comment]
thanks,我忘记开etcd了...
