### ISSUE TITLE
关于 exclude 的问题

### ISSUE THREAD

**Issue by lycheng** [shunfei/cronsun#70]
https://github.com/shunfei/cronsun/blob/520a61d6c50cbd1f49bfd51a51e4b1e17512d3f1/job.go#L630-L634

你好，我在看代码的时候发现这个循环是不是写的有问题，无论有没选中 excluded 的节点，这个循环好像没起到任何作用？

**Comment by Doflatango** [comment]
这里有 bug，已经修复了，还未发版。

**Comment by lycheng** [comment]
好的，谢谢了
