### ISSUE TITLE
v0.3.1启动错误

### ISSUE THREAD

**Issue by mahonlee** [shunfei/cronsun#71]
Please answer these questions before submitting your issue. Thanks!
在你提交 issue 前，请先回答以下问题，谢谢！

1. What version of Go and cronsun version are you using?
v0.3.1

2. What operating system and processor architecture are you using (`go env`)?
centos 7 amd64

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
下载了最新的v0.3.1 启动后出现这个错误
 ERROR   web/server.go:38        Init Config failed: 替换json配置[mail.json]失败：invalid character 'l' after object key:value pair 

4. What did you expect to see?
请问如何解决

5. What did you see instead?
现在你得到的结果是什么样的？

**Comment by mahonlee** [comment]
没有修改过任何东西，直接解压运行 就出错了

**Comment by Doflatango** [comment]
你把 mail.json 的这一行删掉先：
```
 "#LocalName": "By default, "localhost" is sent.",
```

**Comment by mahonlee** [comment]
@Doflatango ok 我试一下
