### ISSUE TITLE
反馈一下v0.3.1版本使用中的一些问题

### ISSUE THREAD

**Issue by mahonlee** [shunfei/cronsun#73]
1. 重启系统后之前设置的任务全部消失
2.节点服务器出现问题的话 控制台需要强制刷新才能看见
3.本次的升级使用没有v0.2.X版本来的好用

**Comment by Doflatango** [comment]
> 重启系统后之前设置的任务全部消失

升级没有删除任务的行为，你看看升级前后 base.json 的配置有没有不一样的？或者连接到另外一个 etcd 集群之类的？
