### ISSUE TITLE
Web服务仅绑定ipv4接口怎么配置

### ISSUE THREAD

**Issue by zjcnew** [shunfei/cronsun#76]
管理节点Web服务不使用ipv6地址，仅启用ipv4，尝试修改配置conf/web.json 
"BindAddr": "0.0.0.0:7079"不生效，ipv6依然被启用。

**Comment by Doflatango** [comment]
所以你是不想指定 IP 但是又想只用 ipv4？

**Comment by zjcnew** [comment]
对的


________________________________
发件人: Doflatango <notifications@github.com>
发送时间: 2018年4月17日 23:07
收件人: shunfei/cronsun
抄送: 从删库到跑路的自我修养; Author
主题: Re: [shunfei/cronsun] Web服务仅绑定ipv4接口怎么配置 (#76)


所以你是不想指定 IP 但是又想只用 ipv4？

―
