### ISSUE TITLE
单机单进程和组级别任务有什么区别？

### ISSUE THREAD

**Issue by kwen94** [shunfei/cronsun#77]
我的测试如下：结果一样，不明白这两种选择的区别在哪。
	任务级别：

		1. 组级别任务：
			定义：在所有选择的节点上选一个节点运行
			测试：
				1. 停止某一node节点，任务在其他机器照常运行，任务没有在这台机器运行
					启动该node节点，任务能被调度到这台机器执行
				2. 停止某一节点的etcd，任务在其他机器照常运行，任务没有在这台机器运行
					启动该节点etcd，任务能被调度到这台机器执行
				3. 停止web节点
					任务正常执行

		2. 单机单进程：
			测试：
				1. 停止某一node节点，任务在其他机器照常运行，任务没有在这台机器运行
					启动该node节点，任务能被调度到这台机器执行
				2. 停止某一节点的etcd，任务在其他机器照常运行，任务没有在这台机器运行
					启动该节点etcd，任务能被调度到这台机器执行
				3. 停止web节点
					任务正常执行

**Comment by QLeelulu** [comment]
请看这里的说明：[任务类型](https://github.com/shunfei/cronsun/wiki/%E4%BB%BB%E5%8A%A1%E9%85%8D%E7%BD%AE#%E4%BB%BB%E5%8A%A1%E7%B1%BB%E5%9E%8B) 。
在

**Comment by kwen94** [comment]
去除了同时有且只有一个任务进程在跑的限制，只要任务调度时间到，就会在某个节点上面开始另一个任务进程。

也就是说组级别任务可能会同时运行两次这个任务？

**Comment by QLeelulu** [comment]
当出现以下情况的时候：

- 任务设定为每隔10秒会执行一次；
- 任务脚本的运行时间为15秒（就是脚本的运行时间大于任务的间隔时间）；

当发生以上情况时，这两种任务类型才会有区别
