### ISSUE TITLE
部署及期望

### ISSUE THREAD

**Issue by dxtywt** [shunfei/cronsun#8]
- [ ] 安装部署
- [ ] 希望增加

## 安装部署
 1、go -> 1.7.4  对应 etcd 要使用release-3.1
 2、一些依赖模块。因为墙的原因，全部手动下载添加，包都不大，建议加在项目包里（http://www.golangtc.com/download/package）
 
## 希望增加login
权限控制，即使内网环境，还是有不少人可以接触到

**Comment by miraclesu** [comment]
关于权限控制，可以试一下我们的反代服务： 
介绍： http://www.cnblogs.com/QLeelulu/p/aproxy.html 
github: https://github.com/shunfei/aproxy

**Comment by QLeelulu** [comment]
楼主已经提到了是内网环境下还可以接触到的，
在这种情况下用了aproxy也是没用的，
权限控制还是可以考虑增加下的

**Comment by peter34861** [comment]
我们也试用了下，功能不错， 用户审计真的很重要，还是建议加上。
