### ISSUE TITLE
能否执行一次性命令?

### ISSUE THREAD

**Issue by slooring** [shunfei/cronsun#82]
不使用cron,类似linux下的at命令

**Comment by Doflatango** [comment]
目前没有定时执行一次就停止的功能。
作为一个临时的选择，你可以创建一个任务，状态选择暂停，然后在具体的时间点手动执行一次，找到任务列表某个任务后面那个循环箭头的图标，就可以立即执行一次了。

**Comment by slooring** [comment]
感谢回复，很遗憾目前没有这个功能

希望能考虑添加这个功能，有一些实际的场景确实只需要定时单次运行任务

比如线上发布，希望在某个指定时间发布某个指定版本到线上。目前使用at命令来管理，如果可以放在cronsun里管理那就太赞啦。

**Comment by QLeelulu** [comment]
#109

**Comment by QLeelulu** [comment]
新发布的 [v0.3.4](https://github.com/shunfei/cronsun/releases/tag/v0.3.4) 已经可以支持一次性命令。
