### ISSUE TITLE
cronsun使用问题

### ISSUE THREAD

**Issue by yanzghaonan** [shunfei/cronsun#85]
Please answer these questions before submitting your issue. Thanks!
在你提交 issue 前，请先回答以下问题，谢谢！

1. What version of Go and cronsun version are you using?
你用的是哪个版本的 Go 和 哪个版本的 cronsun？
0.3.1
2. What operating system and processor architecture are you using (`go env`)?
你用的是哪个操作系统，什么架构的？
centos7.4

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
你做了什么，遇到了什么问题？尽可能描述清楚问题，最好把操作步骤写下来，按这些步骤操作后能重现你的问题。
mongodb出现问题重启后恢复正常，所有node节点不能自动加入，需要重启node节点，web界面才可以看到新加入的这个节点

4. What did you expect to see?
你期望得到什么样的结果？
ndoe没有有自动检测，比如说连接不上mongodb设置超时时间，多久之后重新连接

5. What did you see instead?
现在你得到的结果是什么样的？
现在都是手动重启，但是当ndoe一定数量的时候会很麻烦

**Comment by yanzghaonan** [comment]
cronsun中mongodb重启后，之前加入的node节点全部掉了，node节点上面可以设置超时时间吗？多长时间连接不上mongodb或者etcd可以重新发起连接。不要每次手动重启服务，这样的话当有很多node的时候万一etcd或者mongodb出现问题会很麻烦

**Comment by miraclesu** [comment]
可以升级 v0.3.2，之后就有同步 node 到 mongodb 的功能了，可以通过执行下面的命令同步
```
csctl node -c=conf/base.json --cmd=sync
```

更详细的信息请查看
```
csctl node --help
Send a command to nodes and execute it.

Available Commands:
  rmold:	remove old version(< 0.3.0) node info from mongodb and etcd
  sync:		sync node info to mongodb

Usage:
  csctl node [flags]

Flags:
      --cmd string       the command send to node
      --exclude string   the node ids that doesn't need to execute the command, split by ',', e.g: '--exclude=aa,bb,cc', empty means none
  -h, --help             help for node
      --include string   the node ids that needs to execute the command, split by ',', e.g: '--include=aa,bb,cc', empty means all nodes

Global Flags:
  -c, --conf string   base.json file path. (default "conf/files/base.json")
```
