### ISSUE TITLE
服务器重启以后，任务列表里面设置的任务全没有了

### ISSUE THREAD

**Issue by mahonlee** [shunfei/cronsun#88]
Please answer these questions before submitting your issue. Thanks!
在你提交 issue 前，请先回答以下问题，谢谢！

1. What version of Go and cronsun version are you using?
v0.2.3

2. What operating system and processor architecture are you using (`go env`)?
centos 7

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

服务器重启以后，再次登录WEB UI界面，任务列表里面设置的任务全没有了，可是日志都在正常的跑，请问怎么回事啊

4. What did you expect to see?
我设置的那么多任务怎么找回呢

5. What did you see instead?
现在你得到的结果是什么样的？

**Comment by Doflatango** [comment]
任务是保存在 etcd 的，你是不是以后动过 cronsun 的配置？或者有没有误删了 etcd 的数据？

**Comment by mahonlee** [comment]
@Doflatango 我是WEB UI和etcd在一个服务器的

**Comment by Doflatango** [comment]
> 任务是保存在 etcd 的。

如果 web 界面看不到任务（且没有报错的话），就说明任务不在指定的地方：
1. 有可能是任务数据真的丢失了，被其他人从 etcd 误删了，或者 etcd 的数据被清了；
2. 还有一个可能是，有人在这之前改了 cronsun etcd 的配置（在 etcd.json），连到其它 etcd 集群或者 key path 被修改了（在 base.json 里面）

**Comment by mahonlee** [comment]
嗯 是的 那请问保持cronnode后台运行和开机启动 有什么好的方法吗？
我开机的时候在/etc/rc.local里面添加了
`/home/cronsun/cronnode -conf base/base.json`
但是经常在web控制台看见故障节点的提示
请教下，您推荐的自启动和后台运行的方法呢？ 可以不用nohup吗

**Comment by Doflatango** [comment]
@mahonlee 你可以用 `supervisor` 来管理进程。

> 但是经常在web控制台看见故障节点的提示

可能是网络不稳定，`cronnode` 节点连接 `etcd` 超时了，这个会导致节点无法正常的维持心跳包，会被当做故障节点。
