### ISSUE TITLE
节点故障

### ISSUE THREAD

**Issue by melpozhang** [shunfei/cronsun#9]
web服务起来后 加了几个节点 包括本机 但是发现除了本机的节点以后 都是显示故障 看上去运行并没有什么问题 这是什么原因

**Comment by miraclesu** [comment]
1. 所有服务都是用的同样的` etcd ` 配置吗？估计配置不一致造成的。 
2. 结点正常运行，但如果后台显示故障的话，从后台增加/修改任务的时候，那些故障结点可能收不到这些任务。

**Comment by melpozhang** [comment]
我etcd都是直接运行的...似乎没改配置,请问下需要什么配置呢?

**Comment by miraclesu** [comment]
> 1. 所有服务都是用的同样的etcd 配置吗？估计配置不一致造成的。
1. 所有服务指的是你部署的 `node` 结点和 `web` 结点
2. `etcd` 的配置指的是 `conf/etcd.json` 里的 `Endpoints` 项，这个得用同一个 `etcd(集群)`，而不是每个结点都用本机上的
3. 看你的描述似乎是每个结点上都有 `etcd`，而且不是集群模式，每个服务连的是本机的 `etcd`，如果是这样的话，`node` 和 `web` 没法通过同一个 `etcd(集群)` 通信，`web` 只能识别本机的 `node` 结点了

**Comment by melpozhang** [comment]
thanks,etcd运行指定IP就好了 第一次接触etcd有点懵,直接运行client url都是localhost了, 现在看来和zk有那么点像
