### ISSUE TITLE
如何增加节点

### ISSUE THREAD

**Issue by zhoud9012** [shunfei/cronsun#91]
Please answer these questions before submitting your issue. Thanks!
在你提交 issue 前，请先回答以下问题，谢谢！

1. What version of Go and cronsun version are you using?
你用的是哪个版本的 Go 和 哪个版本的 cronsun？

2. What operating system and processor architecture are you using (`go env`)?
你用的是哪个操作系统，什么架构的？

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
你做了什么，遇到了什么问题？尽可能描述清楚问题，最好把操作步骤写下来，按这些步骤操作后能重现你的问题。

4. What did you expect to see?
你期望得到什么样的结果？

5. What did you see instead?
现在你得到的结果是什么样的？

**Comment by zhoud9012** [comment]
请问如何增加cornsun节点？

**Comment by zqhong** [comment]
https://github.com/shunfei/cronsun/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98%E5%8F%8A%E6%95%85%E9%9A%9C%E6%8E%92%E9%99%A4

请仔细阅读 wiki。

---

如何添加新节点？
拷贝所有配置到新到机器上面，直接启动 `cronnode` 即可。
