### ISSUE TITLE
25分钟的定时任务，在x:50时，下次执行只会在x+1:00执行

### ISSUE THREAD

**Issue by aboutbo** [shunfei/cronsun#95]
1. What version of Go and cronsun version are you using?
你用的是哪个版本的 Go 和 哪个版本的 cronsun？
v0.3.2(build go 1.10.2)

2. What operating system and processor architecture are you using (`go env`)?
CentOS Linux release 7.2.1511 (Core) 3.10.0-229.14.1.el7.x86_64

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
配置了每25分钟执行一次的定时任务，比如任务在6:00，6:25，6:50，正常运行，下次任务运行时间
会在7:00执行，没有间隔25分钟。
![image](https://user-images.githubusercontent.com/13026505/42978215-45e1b93c-8bfe-11e8-9a49-2bf7f31a8b01.png)

**Comment by QLeelulu** [comment]
跑任务的cronnode节点机器的时间没有更改过 ？

**Comment by aboutbo** [comment]
@QLeelulu cronnode和cronweb都在一台机器上部署的，只有一个结点跑任务，没有修改过时间

**Comment by QLeelulu** [comment]
麻烦发下这个任务对应的定时规则吧。

**Comment by Doflatango** [comment]
关于 cron 里面的 `/` 的规则描述，我觉得[文档](https://github.com/shunfei/cronsun/wiki/%E4%BB%BB%E5%8A%A1%E9%85%8D%E7%BD%AE#%E5%AE%9A%E6%97%B6%E5%99%A8)里面的这个描述比较好理解：
> /： 匹配指定的数字，如 */3 在小时字段中等于 0,3,6,9,12,15,18,21 等被 3 整除的数；

其实这个步长(step value)计数范围是不超过 1 分钟/小时/天... 的，就是说会在 0 的时候被重置开始计算。

**Comment by aboutbo** [comment]
@Doflatango 我觉得我的问题原因可能就是在这，是我误用了
这是定时任务的规则0 */25 * * * *
